preview:
    hugo serve --buildDrafts --buildExpired --buildFuture --navigateToChanged

USER:='root'
HOST:='1.1.1.1'
DIR:='/srv/folder'

deploy:
    hugo --minify
    rsync -rvz --delete public/ {{USER}}@{{HOST}}:{{DIR}} # this will delete everything on the server that's not in the local public folder
